FROM arm32v7/node:18.18.2-alpine

# update apt-get sources
RUN apt-get update 
RUN apt-get -y dist-upgrade

# RUN mkdir -p /data/db
# VOLUME ["/data/db"]
# EXPOSE 27017
# ENTRYPOINT ["/usr/bin/mongod"]
